runner:
  insecure: true
  network: "gitea-net"

container:
  network: "gitea-net"

  extra_hosts:
    - "gitea:172.19.0.30"
    - "gitea.local:172.19.0.30"

  # Разрешаем использовать системную директорию хост-машины
  valid_volumes:
    - "/etc/ssl/certs"

  # Монтируем проверенную системную папку хоста с сертификатами прямо в контейнеры джоб
  options: "--mount type=bind,source=/etc/ssl/certs,target=/etc/ssl/certs,readonly"

  env:
    GIT_SSL_NO_VERIFY: "true"
    NODE_TLS_REJECT_UNAUTHORIZED: "0"
